print('='*30)
print('hi')
print('='*30)
print()
print('VS Code let us very convenient via two commands')
print()
print('The first one is "Alt+Shift+Arrows"')
print('It allows us to copy one row very easily.')
print()
print('The another one is "Alt+Arrows')
print('It moves one line up and down.')